name: projet_8016586
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.3.3 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.1  # Utilisez la dernière version disponible
  sqflite: ^2.3.0
  shelf: ^1.4.1
  postgres: ^2.4.4
  path_provider: ^2.1.2
  path: ^1.8.3
  projet_8016586_f2f:
    git: https://f2f.bostonux.com/packages/projet_8016586_f2f
  provider: ^6.1.4
  window_manager: ^0.4.3
  sqflite_common_ffi: ^2.3.5
  sqlite3: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
flutter:
  uses-material-design: true
  assets:
    - lib/assets/Images/logooo.svg
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/Fonts/Poppins/Poppins-Regular.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/Fonts/Poppins/Poppins-Italic.ttf
          style: italic